### PR TITLE
Perform apt-get non-interactively

### PR DESCRIPTION
**Pull request by gmacario**
See http://askubuntu.com/questions/556385/how-can-i-install-apt-packages-non-interactively

Signed-off-by: Gianpaolo Macario gianpaolo_macario@mentor.com

### CODE REVIEW

**Comment by gunnarx** [comment]
Thanks, this is interesting.  I've been trying this out but I'm not sure it had a big effect on the error messages during apt-get provisioning. Have you been able to confirm that it improves something?

I think it needs some further testing but that's a bit lower priority than new features now.  Anyway, let me know if you have more information and I will note this in the appropriate issue.

**Comment by gunnarx** [comment]
I no longer remember if I tested this successfully, but I don't want to keep the PR open, and it's harmless as far as I know.

**Comment by gmacario** [comment]
Hi @gunnarx,

Thanks for merging my PR

**Comment by gunnarx** [comment]
Haha, only took 2.5 years. Yeah I was basically doing some cleanup today...

**Pull request merged**
